export {default as Card1} from './Card1'
export {default as Card2} from './Card2'
export {default as Card3} from './Card3'
export * from './changePassword'
export * from './changeName'
export * from './Help'
export * from './Logout'
export * from './Settings'
export * from './Address'