export const types = {
    REGISTER_NEEDY_START:'REGISTER_NEEDY_START',
    REGISTER_NEEDY_FAILED:'REGISTER_NEEDY_FAILED',
    REGISTER_NEEDY_SUCCESS:'REGISTER_NEEDY_SUCCESS',

    REGISTER_DONOR_START:'REGISTER_DONOR_START',
    REGISTER_DONOR_FAILED:'REGISTER_DONOR_FAILED',
    REGISTER_DONOR_SUCCESS:'REGISTER_DONOR_SUCCESS',

}