export const types = {
    REGISTER_NEEDY_START:'REGISTER_NEEDY_START',
    REGISTER_NEEDY_FAILED:'REGISTER_NEEDY_FAILED',
    REGISTER_NEEDY_SUCCESS:'REGISTER_NEEDY_SUCCESS',

    REGISTER_DONOR_START:'REGISTER_DONOR_START',
    REGISTER_DONOR_FAILED:'REGISTER_DONOR_FAILED',
    REGISTER_DONOR_SUCCESS:'REGISTER_DONOR_SUCCESS',

    LOGIN_START:'LOGIN_START',
    LOGIN_FAILED:'LOGIN_FAILED',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',

    GET_NEEDY_START:'GET_NEEDY_START',
    GET_NEEDY_FAILED:'GET_NEEDY_FAILED',
    GET_NEEDY_SUCCESS:'GET_NEEDY_SUCCESS',

    GET_DONOR_START:'GET_DONOR_START',
    GET_DONOR_FAILED:'GET_DONOR_FAILED',
    GET_DONOR_SUCCESS:'GET_DONOR_SUCCESS',

    VIEW_NEARBY_ADS_START:'VIEW_NEARBY_ADS_START',
    VIEW_NEARBY_ADS_FAILED:'VIEW_NEARBY_ADS_FAILED',
    VIEW_NEARBY_ADS_SUCCESS:'VIEW_NEARBY_ADS_SUCCESS',

    VIEW_BOOKEDADS_START:'VIEW_BOOKEDADS_START',
    VIEW_BOOKEDADS_FAILED:'VIEW_BOOKEDADS_FAILED',
    VIEW_BOOKEDADS_SUCCESS:'VIEW_BOOKEDADS_SUCCESS',

    VIEW_BOOKED_DONOR_ADS_START:'VIEW_BOOKED_DONOR_ADS_START',
    VIEW_BOOKED_DONOR_ADS_FAILED:'VIEW_BOOKED_DONOR_ADS_FAILED',
    VIEW_BOOKED_DONOR_ADS_SUCCESS:'VIEW_BOOKED_DONOR_ADS_SUCCESS',

    UPDATE_PASSWORD_START:'UPDATE_PASSWORD_START',
    UPDATE_PASSWORD_FAILED:'UPDATE_PASSWORD_FAILED',
    UPDATE_PASSWORD_SUCCESS:'UPDATE_PASSWORD_SUCCESS',

    UPDATE_NAME_START:'UPDATE_NAME_START',
    UPDATE_NAME_FAILED:'UPDATE_NAME_FAILED',
    UPDATE_NAME_SUCCESS:'UPDATE_NAME_SUCCESS',

    UPDATE_PRIVATE_START:'UPDATE_PRIVATE_START',
    UPDATE_PRIVATE_FAILED:'UPDATE_PRIVATE_FAILED',
    UPDATE_PRIVATE_SUCCESS:'UPDATE_PRIVATE_SUCCESS',

    UPDATE_MESSAGES_START:'UPDATE_MESSAGES_START',
    UPDATE_MESSAGES_FAILED:'UPDATE_MESSAGES_FAILED',
    UPDATE_MESSAGES_SUCCESS:'UPDATE_MESSAGES_SUCCESS',


    UPDATE_ADDRESS_START:'UPDATE_ADDRESS_START',
    UPDATE_ADDRESS_FAILED:'UPDATE_ADDRESS_FAILED',
    UPDATE_ADDRESS_SUCCESS:'UPDATE_ADDRESS_SUCCESS',

    BOOK_DONATION_START:'BOOK_DONATION_START',
    BOOK_DONATION_FAILED:'BOOK_DONATION_FAILED',
    BOOK_DONATION_SUCCESS:'BOOK_DONATION_SUCCESS',

    CANCEL_DONATION_START:'CANCEL_DONATION_START',
    CANCEL_DONATION_FAILED:'CANCEL_DONATION_FAILED',
    CANCEL_DONATION_SUCCESS:'CANCEL_DONATION_SUCCESS',

    ADD_DONATION_START:'ADD_DONATION_START',
    ADD_DONATION_FAILED:'ADD_DONATION_FAILED',
    ADD_DONATION_SUCCESS:'ADD_DONATION_SUCCESS',

    GET_CATEGORY_START:'GET_CATEGORY_START',
    GET_CATEGORY_FAILED:'GET_CATEGORY_FAILED',
    GET_CATEGORY_SUCCESS:'GET_CATEGORY_SUCCESS',

    COMPLETE_DONATION_START:'COMPLETE_DONATION_START',
    COMPLETE_DONATION_FAILED:'COMPLETE_DONATION_FAILED',
    COMPLETE_DONATION_SUCCESS:'COMPLETE_DONATION_SUCCESS',

    SHOW_TOAST:'SHOW_TOAST',
    HIDE_TOAST:'HIDE_TOAST',
}