export const types = {
    REGISTER_NEEDY_START:'REGISTER_NEEDY_START',
    REGISTER_NEEDY_FAILED:'REGISTER_NEEDY_FAILED',
    REGISTER_NEEDY_SUCCESS:'REGISTER_NEEDY_SUCCESS',

    REGISTER_DONOR_START:'REGISTER_DONOR_START',
    REGISTER_DONOR_FAILED:'REGISTER_DONOR_FAILED',
    REGISTER_DONOR_SUCCESS:'REGISTER_DONOR_SUCCESS',

    LOGIN_START:'LOGIN_START',
    LOGIN_FAILED:'LOGIN_FAILED',
    LOGIN_SUCCESS:'LOGIN_SUCCESS',

    SHOW_TOAST:'SHOW_TOAST',
    HIDE_TOAST:'HIDE_TOAST',
}